client_id = "34cfa6dff5756c50a615d574196baac1"

name = "Invoice / Vies Check"
handle = "invoice-vies-check"

application_url = "https://invoice-vies-check.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[access_scopes]
scopes = "write_customers,read_customers,read_orders,write_orders,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://invoice-vies-check.onrender.com/auth/callback",
  "https://invoice-vies-check.onrender.com/auth/shopify/callback",
  "https://invoice-vies-check.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[app_proxy]
url = "https://invoice-vies-check.onrender.com/apps/invoice-request"
subpath = "invoice-request"
prefix = "apps"