client_id = "0b1e948821dbee54d55007ae22311cc2"
name = "Invoice Request / VIES Check"
application_url = "https://faber-invoice-vies-check.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
scopes = "read_customers,write_customers,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://faber-invoice-vies-check.onrender.com/auth/callback",
  "https://faber-invoice-vies-check.onrender.com/api/auth/callback",
  "https://faber-invoice-vies-check.onrender.com/api/auth"
]

[app_proxy]
url = "https://faber-invoice-vies-check.onrender.com/apps/invoice-request"
subpath = "invoice-request"
prefix = "apps"